### ISSUE TITLE
Speed Dial buttons do not work on tap. (Samsung S4, Chrome)

### ISSUE THREAD

**Issue by hollburg** [route360/r360-demo#16] opened 2016-07-15 07:52 UTC

**Comment by j-slvr** [comment] 2016-08-10 10:24
see #12

**Comment by gerbsen** [comment] 2016-08-10 10:24
duplicate of #12

**Comment by j-slvr** [comment] 2016-08-10 11:52
fixed

**Comment by j-slvr** [comment] 2016-08-10 11:52
fixed

**Closed by j-slvr** 2016-08-10 11:52 UTC
Labels: duplicate
